# Generated by Django 4.1.7 on 2023-05-27 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.area')),
            ],
        ),
        migrations.CreateModel(
            name='LocalAssembly',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.district')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('max_age', models.PositiveIntegerField()),
                ('min_age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PentecostAdmin',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NationalAdmin',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.nation')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.TextField()),
                ('phone2', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('local_assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.localassembly')),
            ],
        ),
        migrations.CreateModel(
            name='LocalAdmin',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('local_assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.localassembly')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictAdmin',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.district')),
            ],
        ),
        migrations.CreateModel(
            name='AreaAdmin',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.area')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.nation'),
        ),
    ]
