# Generated by Django 4.1.7 on 2023-06-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.TextField(default=models.TextField()),
        ),
    ]
