# Generated by Django 4.1.7 on 2023-07-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0004_nationalannouncement_localannouncement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtannouncement',
            name='district',
        ),
        migrations.RemoveField(
            model_name='localannouncement',
            name='local',
        ),
        migrations.RemoveField(
            model_name='nationalannouncement',
            name='nation',
        ),
        migrations.DeleteModel(
            name='AreaAnnouncement',
        ),
        migrations.DeleteModel(
            name='DistrictAnnouncement',
        ),
        migrations.DeleteModel(
            name='LocalAnnouncement',
        ),
        migrations.DeleteModel(
            name='NationalAnnouncement',
        ),
    ]
