# Generated by Django 4.1.7 on 2023-07-04 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0005_remove_districtannouncement_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalAnnouncement',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.nation')),
            ],
        ),
        migrations.CreateModel(
            name='LocalAnnouncement',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.localassembly')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictAnnouncement',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.district')),
            ],
        ),
        migrations.CreateModel(
            name='AreaAnnouncement',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.area')),
            ],
        ),
    ]
