# Generated by Django 4.1.7 on 2023-07-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0006_nationalannouncement_localannouncement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalEvent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.nation')),
            ],
        ),
        migrations.CreateModel(
            name='LocalEvent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.localassembly')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictEvent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.district')),
            ],
        ),
        migrations.CreateModel(
            name='AreaEvent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.area')),
            ],
        ),
    ]
