# Generated by Django 4.1.7 on 2023-07-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0007_nationalevent_localevent_districtevent_areaevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaevent',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='districtevent',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='localevent',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nationalevent',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
    ]
