# Generated by Django 4.1.7 on 2023-07-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0008_areaevent_venue_districtevent_venue_localevent_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaevent',
            name='image',
            field=models.ImageField(default='events/default_event.jpg', upload_to='events/'),
        ),
        migrations.AddField(
            model_name='districtevent',
            name='image',
            field=models.ImageField(default='events/default_event.jpg', upload_to='events/'),
        ),
        migrations.AddField(
            model_name='localevent',
            name='image',
            field=models.ImageField(default='events/default_event.jpg', upload_to='events/'),
        ),
        migrations.AddField(
            model_name='nationalevent',
            name='image',
            field=models.ImageField(default='events/default_event.jpg', upload_to='events/'),
        ),
    ]
