# Generated by Django 4.1.7 on 2023-07-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0009_areaevent_image_districtevent_image_localevent_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areaevent',
            old_name='date',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='districtevent',
            old_name='date',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='localevent',
            old_name='date',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='nationalevent',
            old_name='date',
            new_name='start',
        ),
    ]
