# Generated by Django 4.1.7 on 2023-07-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0010_rename_date_areaevent_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaevent',
            name='end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='districtevent',
            name='end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='localevent',
            name='end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='nationalevent',
            name='end',
            field=models.DateField(default=None),
        ),
    ]
