# Generated by Django 4.1.7 on 2023-07-09 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0013_alter_areaevent_end_alter_districtevent_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaevent',
            name='end',
            field=models.DateField(default=datetime.datetime.now, null=True),
            preserve_default=False
        ),
        migrations.AlterField(
            model_name='districtevent',
            name='end',
            field=models.DateField(default=datetime.datetime.now, null=True),
            preserve_default=False
        ),
        migrations.AlterField(
            model_name='localevent',
            name='end',
            field=models.DateField(default=datetime.datetime.now, null=True),
            preserve_default=False
        ),
        migrations.AlterField(
            model_name='nationalevent',
            name='end',
            field=models.DateField(default=datetime.datetime.now, null=True),
            preserve_default=False
        ),
    ]
