# Generated by Django 4.1.7 on 2023-07-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0014_alter_areaevent_end_alter_districtevent_end_and_more'),
    ]

    operations = [
    ]
