# Generated by Django 4.1.7 on 2023-07-25 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0015_auto_20230709_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaevent',
            name='end',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='districtevent',
            name='end',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='end',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='nationalevent',
            name='end',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('password', models.TextField(default=models.TextField())),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecop_app.nation')),
            ],
        ),
    ]
