# Generated by Django 4.1.7 on 2023-07-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0016_alter_areaevent_end_alter_districtevent_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(default='2004-02-18'),
        ),
    ]
