# Generated by Django 4.1.7 on 2023-07-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0017_remove_member_age_member_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(default='2004-02-18'),
        ),
    ]
