# Generated by Django 4.1.7 on 2023-07-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0021_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='title',
            field=models.CharField(default='Lyrics', max_length=100),
        ),
    ]
