# Generated by Django 4.1.7 on 2023-08-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thecop_app', '0022_songs_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('img', models.ImageField(upload_to='article_imgs')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('head', models.CharField(max_length=500)),
                ('brief', models.CharField(default='', max_length=500)),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
